version: '3.8'

services:
  web:
    image: nginx:alpine
    platform: linux/amd64
    container_name: datrix-web
    ports:
      - "8081:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
    restart: unless-stopped
